<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Action class {class} must implement the "run" method.' => '',
  '&lt; Previous' => '@@@@',
  '&lt;&lt; First' => '@@@@',
  'CApcCache requires PHP apc extension to be loaded.' => '@@@@',
  'CMemCache server configuration must be an array.' => '@@@@',
  'CMemCache server configuration must have "host" value.' => '@@@@',
  'Go to page: ' => '@@@@',
  'Last &gt;&gt;' => '@@@@',
  'Next &gt;' => '@@@@',
  'The "forceCopy" and "linkAssets" cannot be both true.' => '@@@@',
  'The asset "{asset}" to be published does not exist.' => '@@@@',
);
