<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Active Cards' => '',
  'Add Card' => '',
  'Add a New Card' => '',
  'Add a content extract here' => '',
  'Analytics' => '',
  'Appearance' => '',
  'Attributes for {{group}}' => '',
  'Blog Post' => '',
  'Burnin\' the midnight oil huh?' => '',
  'By: {{user}}' => '',
  'Cache' => '',
  'Categories' => '',
  'Change User Information' => '',
  'Change information for {{user}}' => '',
  'CiiMS Dashboard | {{pagetitle}}' => '',
  'CiiMS Version' => '',
  'Click to view options' => '',
  'Configure various features and behaviors for your site.' => '',
  'Content' => '',
  'Content Settings' => '',
  'Create a New Category' => '',
  'Create or modify information for this category' => '',
  'Dashboard' => '',
  'Dashboard Cards' => '',
  'Database' => '',
  'Delete Selected' => '',
  'Draft' => '',
  'Email' => '',
  'Email To Test' => '',
  'Enter the user/repo of where the widget you want to upload is located at.' => '',
  'Enter your post title here' => '',
  'Filter by Name' => '',
  'Flush CiiMS Cache' => '',
  'General' => '',
  'Good afternoon' => '',
  'Good evening' => '',
  'Good morning' => '',
  'Invite Users' => '',
  'Issues With CiiMS' => '',
  'Makes Changes to {{group}}' => '',
  'Manage Categories' => '',
  'Manage Content' => '',
  'Manage Users' => '',
  'Manage users, user metadata, and permissions' => '',
  'Manage users, user metadata, and permissions.' => '',
  'Markdown' => '',
  'Mobile Theme' => '',
  'Mornin\' Sunshine!' => '',
  'PHP Version' => '',
  'Page' => '',
  'Password (Optional)' => '',
  'Plugins' => '',
  'Preview' => '',
  'Repository' => '',
  'Rich Text' => '',
  'Save Changes' => '',
  'Scheduled for {{date}}' => '',
  'Send a Test Email' => '',
  'Set or change a user\'s password. Otherwise leave blank' => '',
  'Settings' => '',
  'Showing {start} through {end} of {count}' => '',
  'Slug' => '',
  'Social' => '',
  'System' => '',
  'System Information' => '',
  'Tablet Theme' => '',
  'Test Email' => '',
  'Theme' => '',
  'There are no themes installed for this category.' => '',
  'This is metadata that has been retrieves from the user. Do not alter this data unless you know what you are doing. It can cause serious damage to the user' => '',
  'Users' => '',
  'Web Server' => '',
  'Welcome back' => '',
  'Working late tonght' => '',
  'Yii Version' => '',
  '{{welcome}}' => '',
  '{{welcome}} {{user}}?' => '',
  '{{welcome}}, {{user}}' => '',
);
