<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About' => '',
  'Activate your Account' => '',
  'All Posts' => '',
  'Appearance' => '',
  'Authenticate' => '',
  'Before you can login to your account we need you to verify your email address. Be on the lookout for an email from {{email}} containing activating instructions.' => '',
  'Categories' => '',
  'Comment has been redacted' => '',
  'Comment on this post' => '',
  'Email Address' => '',
  'Error {{code}}' => '',
  'Forgot Your Password?' => '',
  'From:' => '',
  'Front Page Image' => '',
  'Heads Up!' => '',
  'Hey there!' => '',
  'Login to Your Account' => '',
  'Looking for something on the blog?' => '',
  'Member since' => '',
  'Menu Items' => '',
  'No Results Found' => '',
  'Number of Tweets to Fetch' => '',
  'Once more with feeling!' => '',
  'Oops!' => '',
  'Or register with one of these social networks' => '',
  'Or sign in with one of these social networks' => '',
  'P.S. If you did not request this email, you may safely ignore it.' => '',
  'Password' => '',
  'Password (again)' => '',
  'Password Required!' => '',
  'Posts By This User' => '',
  'Read more' => '',
  'Recent Posts' => '',
  'Register' => '',
  'Register An Account' => '',
  'Related Posts' => '',
  'Search' => '',
  'Search...' => '',
  'Set a password here to change. Leave blank to keep existing password.' => '',
  'Sorry, we tried looking but we didn\'t find a match for the specified criteria. Try refining your search.' => '',
  'Submit' => '',
  'Tags' => '',
  'Thank you.' => '',
  'Thanks for Registering!' => '',
  'Thanks for registering your account at CiiMS Blog {{blog}}. To verify your account, {{clickhere}}. This action will verify your email address and allow you to interact with features only available to registered users.' => '',
  'The password reset key you provided is either invalid or has expired.' => '',
  'This Post Requires a Password to View' => '',
  'This is a notification informing you a new comment has been add on your post: {{title}}.' => '',
  'Twitter Handle' => '',
  'Twitter Settings' => '',
  'Type to search, then press enter' => '',
  'Update Your Profile' => '',
  'Username' => '',
  'Woah!' => '',
  'You recently notified us that you forgot your password for the following blog: {{blog}}. To reset your password, {{clickhere}} and follow the instructions on the reset page. This link is valid for 15 minutes.' => '',
  'Your email address (you@example.com)' => '',
  'Your new password' => '',
  'by' => '',
  'click here' => '',
  'edit' => '',
  'edit your profile' => '',
  'forgot' => '',
  'login' => '',
  'logout' => '',
  'more' => '',
  'register' => '',
  'signup' => '',
  '{{by}} {{author}}' => '',
  '{{count}} Comments' => '',
  '{{count}} Post(s)' => '',
  '{{from}} {{user}}' => '',
  '{{headsup}} Looks like you\'re already logged in as {{email}}. You should {{logout}} before logging in to another account.' => '',
  '{{heythere}} Before leaving a comment you must {{signup}} or {{register}}' => '',
  '{{oops}} It looks like there were a few errors in your submission' => '',
  '{{oops}} It looks like you haven\'t provided any information about yourself yet. Why don\'t you {{edityourprofile}} and add some information about yourself?' => '',
  '{{oops}} This user hasn\'t added any information about themself yet.' => '',
  '{{oops}} We weren\'t able to log you in using the provided credentials.' => '',
  '{{woah}} It looks like there aren\'t any posts in this category yet. Why don\'t you check out some of our other pages or check back later?' => '',
);
