<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'A user with that email address already exists.' => '',
  'A user with the id of {{id}} was not found.' => '',
  'An unexpected error occured fulfilling your request.' => '',
  'An unexpected error occured while deleting the token. Please re-generate a new token for subsequent requests.' => '',
  'Application name must be defined.' => '',
  'The email address you provided is invalid.' => '',
  'Unable to authenticate.' => '',
  'You do not have sufficient privileges to create a new user.' => '',
  'You\'ve Been Invited To Join a Blog!' => '',
);
