<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'All Content' => '',
  'Blogroll' => '',
  'Incorrect password' => '',
  'Liked saved' => '',
  'Password Required' => '',
  'The article you specified does not exist. If you bookmarked this page, please delete it.' => '',
  'The requested post cannot be found.' => '',
  'The specified post cannot be found.' => '',
  'Too many password attempts. Please try again in 5 minutes' => '',
  'Unable to access post' => '',
  'Unable to save like' => '',
  'Unable to save user like' => '',
  '{{app_name}} | {{label}}' => '',
);
