<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Activate Your Account' => '',
  'Activation was successful! You may now {{login}}' => '',
  'An email has been sent to {{email}} with further instructions on how to reset your password' => '',
  'Change Your Email Address' => '',
  'Enter the password you used to register your account to verify your email address.' => '',
  'Error' => '',
  'Error {{code}}' => '',
  'Login' => '',
  'Login to your account' => '',
  'Please provide the password you used during the signup process.' => '',
  'Registration Successful' => '',
  'Search' => '',
  'Sign Up' => '',
  'The activation key your provided was invalid.' => '',
  'The email address has already been associated to an account. Do you want to login instead?' => '',
  'The email your provided is not a valid email address.' => '',
  'The password you provided must be at least 8 characters.' => '',
  'The passwords you provided do not match.' => '',
  'The request to change your email has expired.' => '',
  'The requested email address has already been taken. Please re-submit your request with a new email address.' => '',
  'There was an error fulfilling your request.' => '',
  'Unable to activate user using the provided details.' => '',
  'We were unable to verify your current password. Please verify your password and try again.' => '',
  'You are not authorized to change this email address.' => '',
  'You must provide your password twice for us to reset your password.' => '',
  'Your email address has been sucessfully changes. Please {{login}} again for the changes to take effect.' => '',
  'Your password has been reset, and you may now login with your new password' => '',
  'login' => '',
  '{{app_name}} | {{label}}' => '',
  '{{app_name}} | {{label}} {{code}}' => '',
);
