<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic ciimessage' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Category Post Count' => '',
  'Content Post Cost' => '',
  'Date Format' => '',
  'Default Language' => '',
  'Discourse' => '',
  'Discourse URL' => '',
  'Display Settings' => '',
  'Disqus' => '',
  'Disqus Shortcode' => '',
  'Force SSL for Secure Areas' => '',
  'Offline Mode' => '',
  'Openstack API Key' => '',
  'Openstack Container Name' => '',
  'Openstack Identity URL' => '',
  'Openstack Region' => '',
  'Openstack Username' => '',
  'Password Strength Settings' => '',
  'Search Post Count' => '',
  'Site Name' => '',
  'Site Settings' => '',
  'Time Format' => '',
  'Upload Settings' => '',
  'Use Discourse Comments' => '',
  'Use Disqus Comments' => '',
  'Use Openstack for Uploads?' => '',
  'Use Rackspace CDN?' => '',
);
