<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Address Issues Before Continuing' => '',
  'All' => '',
  'As a reminder, now would be a good time to secure your installation. Details on how to secure your installation can be found {{github}}. I hope you enjoy using CiiMS!' => '',
  'Before CiiMS can continue with the installation, the following issues need to be addressed.' => '',
  'Begin Download' => '',
  'Check' => '',
  'Check MySQL Connection' => '',
  'CiiMS Installer' => '',
  'CiiMS has encountered an error during the installation that requires manual intervention.' => '',
  'CiiMS has finished the installation, you are now ready to login. Click the login button below to login to your site.' => '',
  'CiiMS is now downloading Yii Framework. When the download has finished, press "Continue With Installation". The button will appear once Yii Framework is installed.' => '',
  'CiiMS is now installing the database. {{donotleave}} A notification will appear when it\'s OK to continue.' => '',
  'CiiMS requires Yii Framework to run. In order to proceed with the installation, we need to know the patch where Yii\'s {{framework}} folder is located at.' => '',
  'Click To Begin' => '',
  'Configuration directory is not writable. This must be corrected before your settings can be applied.' => '',
  'Continue' => '',
  'Continue With Installation' => '',
  'Could Not Complete Migration' => '',
  'Create' => '',
  'Create Admin User' => '',
  'DO NOT LEAVE THIS PAGE UNTIL THE DOWNLOAD HAS COMPLETED.' => '',
  'DO NOT LEAVE THIS PAGE UNTIL THE PROCESS HAS COMPLETED.' => '',
  'Database Host' => '',
  'Database Migration in Progress...' => '',
  'Database Name' => '',
  'Display Name' => '',
  'Don\'t have Yii installed already? That\'s OK, CiiMS can download it for you. Before we begin, make sure CiiMS has write permissions to the following directory.' => '',
  'Downloading Yii Framework' => '',
  'Downloading Yii...' => '',
  'Email' => '',
  'Email Address' => '',
  'First Name' => '',
  'Horray!' => '',
  'If you don\'t have a MySQL database setup yet, please do so now, then return to this page.' => '',
  'If you still get stuck, write down everything you did and submit an issue at {{github}}.' => '',
  'Install Yii' => '',
  'Install Yii for Me' => '',
  'Last Name' => '',
  'Lets Get Started' => '',
  'Lets setup your first admin user, and set a few site settings. All of these settings can be changed later in the admin panel.' => '',
  'Login' => '',
  'Migration Complete!' => '',
  'Most likely the error above is a permission error. You can correct this by making the following {{assets}, {{runtime}} and {{config}} directories writable.' => '',
  'Oh Snap!' => '',
  'Password' => '',
  'Press the "back" button in your browser to go back to the previous page and try whatever action you last performed again.' => '',
  'Press the button below and let CiiMS figure out what you need to do next.' => '',
  'Proceed' => '',
  'Review Previous Instructions' => '',
  'Site Name' => '',
  'Thanks for choosing CiiMS!' => '',
  'The following error was produced during the installation.' => '',
  'There was an error saving your details to the database.' => '',
  'Things to Fix Before Proceeding' => '',
  'This installer will walk you through the installation of CiiMS. This process should only take around 5 minutes, but could take longer depending upon your configuration.' => '',
  'Unable to connect to database using the provided credentials.' => '',
  'Username' => '',
  'Warning!' => '',
  'When you have addressed the issue above, refresh the page to continue with the installation.' => '',
  'Where is Yii Framework At?' => '',
  'You can modify the permissions via FTP or from terminal. On Linux, you can run the following command to correct the permissions.' => '',
  'framework' => '',
  'github' => '',
  'on github' => '',
  '{all} Done!' => '',
  '{connect} to MySQL Database' => '',
  '{create} Admin User' => '',
  '{install} and Migrate Database' => '',
  '{woah} An error occured!' => '',
  '{{horray}} The database has been installed. Press the "Continue" button below to create an admin user.' => '',
  '{{ohsnap}} Looks like the database istallations failed failed. Most likely this is an issue with your database connection. Alternatively, you could try running the migrations from the command line.' => '',
  '{{warning}} CiiMS doesn\'t have permissions to write to the runtime directory. Please correct this using the information below before continuing.' => '',
  '{{warning}} There was an an issue downloading and installing Yii Framework. Please verify the permissions are set correctly before attempting again.' => '',
  '{{warning}} {{error}}' => '',
);
