<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'An administrator at {{blog}} has invited you to collaborate at their site at {{site}}. To accept this invitation and to setup your account, click the following link {{link}}.' => '',
  'CiiMS Email Change Notification' => '',
  'CiiMS Test Email' => '',
  'Hello {{user}},' => '',
  'Hello,' => '',
  'If you did NOT request this change, you may safely ignore this email. This request will automatically expired in three (3) days.' => '',
  'If you do not wish to accept this invite, you may safely disregard this email.' => '',
  'If you have recieved this email then your CiiMS instance is capable of sending out emails. No further action or changes is required on your part.' => '',
  'If you requested this change, please visit {{link}} to verify your new email address. Your email address will not be changed until you complete the verification process.' => '',
  'Thank You,' => '',
  'This a security notification from CiiMS. A request has been made on your behalf to change the email address associated to your account.' => '',
  'You\'ve Been Invited...' => '',
  '{{sitename}} Management' => '',
);
