<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Active Cards' => '',
  'Add a content extract here' => '',
  'Analytics' => '',
  'Appearance' => '',
  'Attributes for {{group}}' => '',
  'Blog Post' => '',
  'Burnin\' the midnight oil huh?' => '',
  'By: {{user}}' => '',
  'Cache' => '',
  'Categories' => '',
  'Change User Information' => '',
  'CiiMS Dashboard | {{pagetitle}}' => '',
  'CiiMS Version' => '',
  'Click to view options' => '',
  'Content' => '',
  'Content Settings' => '',
  'Create a New Category' => '',
  'Dashboard' => '',
  'Dashboard Cards' => '',
  'Database' => '',
  'Do not alter this data unless you know what you are doing.' => '',
  'Draft' => '',
  'Email' => '',
  'Email To Test' => '',
  'Enter your post title here' => '',
  'Filter by Name' => '',
  'Flush CiiMS Cache' => '',
  'General' => '',
  'Good afternoon' => '',
  'Good evening' => '',
  'Good morning' => '',
  'Install Addon' => '',
  'Installing Addon...' => '',
  'Instance ID' => '',
  'Issues With CiiMS' => '',
  'Makes Changes to {{group}}' => '',
  'Manage Categories' => '',
  'Manage Users' => '',
  'Managed Themes' => '',
  'Markdown' => '',
  'Mobile Theme' => '',
  'Mornin\' Sunshine!' => '',
  'PHP Version' => '',
  'Page' => '',
  'Password (Optional)' => '',
  'Plugins' => '',
  'Preview' => '',
  'Ready for Review' => '',
  'Save Changes' => '',
  'Scheduled for {{date}}' => '',
  'Search by title' => '',
  'Search for Cards...' => '',
  'Search for Themes...' => '',
  'Send a Test Email' => '',
  'Set or change a user\'s password. Otherwise leave blank' => '',
  'Settings' => '',
  'Slug' => '',
  'Social' => '',
  'Success! Refresh the page to see your changes.' => '',
  'System' => '',
  'System Information' => '',
  'Tablet Theme' => '',
  'Test Email' => '',
  'Theme' => '',
  'There are no themes installed for this category.' => '',
  'This Addon is already installed.' => '',
  'Uninstalled Cards' => '',
  'Uninstalled Themes' => '',
  'User Information' => '',
  'Users' => '',
  'Web Server' => '',
  'Welcome back' => '',
  'Working late tonght' => '',
  'Yes' => '',
  'Yii Version' => '',
  '{{welcome}}' => '',
  '{{welcome}} {{user}}?' => '',
  '{{welcome}}, {{user}}' => '',
);
