<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About' => '',
  'Activate your Account' => '',
  'Before you can login to your account we need you to verify your email address. Be on the lookout for an email from {{email}} containing activating instructions.' => '',
  'By:' => '',
  'By: {{author}}' => '',
  'Categories' => '',
  'Change Your Email Address' => '',
  'Create Your Account' => '',
  'Dashboard' => '',
  'Did you forget your password? Enter your email address below and we\'ll send you an email link that will allow you to reset your password.' => '',
  'Display Name' => '',
  'Email Address' => '',
  'Error {{code}}' => '',
  'First Name' => '',
  'Forgot Your Password?' => '',
  'Heads Up!' => '',
  'Home' => '',
  'Last Name' => '',
  'Login to Your Account' => '',
  'No Results Found' => '',
  'Once more with feeling!' => '',
  'Oops!' => '',
  'Or register with one of these social networks' => '',
  'Or sign in with one of these social networks' => '',
  'Password' => '',
  'Password (again)' => '',
  'Read More' => '',
  'Recent Comments' => '',
  'Recent Posts' => '',
  'Register an Account' => '',
  'Registered' => '',
  'Related Posts' => '',
  'Reputation' => '',
  'Set a password for the user here. Leave blank to keep existing password.' => '',
  'Sorry, we tried looking but we didn\'t find a match for the specified criteria. Try refining your search.' => '',
  'Submit' => '',
  'Tags' => '',
  'Tell us about yourself' => '',
  'Thanks for Activating Your Account!' => '',
  'Thanks for Registering!' => '',
  'The password reset key you provided is either invalid or has expired.' => '',
  'This user has not provided any information for themselves.' => '',
  'To accept your invitation, set your account details here.' => '',
  'To change the email address associated to your account, please enter your current password.' => '',
  'Type to search, then press enter' => '',
  'Username' => '',
  'Woah!' => '',
  'You may now {{login}} and head to the {{dashboard}}' => '',
  'Your current password' => '',
  'Your email address (you@example.com)' => '',
  'Your new password' => '',
  'dashboard' => '',
  'edit' => '',
  'forgot' => '',
  'login' => '',
  'logout' => '',
  'register' => '',
  '{{headsup}} Looks like you\'re already logged in as {{email}}' => '',
  '{{headsup}} Looks like you\'re already logged in as {{email}}. You should {{logout}} before logging in to another account.' => '',
  '{{oops}} There were errors in your form submission. Please correct the items in red below.' => '',
  '{{oops}} We weren\'t able to log you in using the provided credentials.' => '',
  '{{woah}} It looks like there aren\'t any posts in this category yet. Why don\'t you check out some of our other pages or check back later?' => '',
);
