<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'A new verification email has been resent to {{user}}. Please check your email address.' => '',
  'Oops! That user doesn\'t exist on our network!' => '',
  'There was an error resending the verification email. Please try again later.' => '',
  'There were errors saving your profile. Please correct them before trying to save again.' => '',
  'User {{user}} - CiiMS | {{sitename}}' => '',
  'Your profile has been updated!' => '',
);
