<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'A password reset link has been sent to your email address' => '',
  'Accept Invitation' => '',
  'Activate Your Account' => '',
  'An email has been sent to {{email}} with further instructions on how to reset your password' => '',
  'Change Your Email Address' => '',
  'Error' => '',
  'Error {{code}}' => '',
  'Forgot Your Password?' => '',
  'Login to your account' => '',
  'Reset Your password' => '',
  'Search' => '',
  'Sign Up' => '',
  'The password reset key provided is invalid' => '',
  'The verification key provided is invalid.' => '',
  'There was an error fulfilling your request.' => '',
  'You have successfully registered an account. Before you can login, please check your email for activation instructions' => '',
  'Your account has successfully been activated. You may now login' => '',
  'Your new email address has been verified.' => '',
  'Your password has been reset, and you may now login with your new password' => '',
  '{{app_name}} | {{label}}' => '',
  '{{app_name}} | {{label}} {{code}}' => '',
);
