<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add to Dashboard' => '',
  'An ID must be specified' => '',
  'An error occured while trying to delete a comment.' => '',
  'Analytics Settings' => '',
  'Appearance' => '',
  'By {{user}}' => '',
  'Cannot delete attribute that does not exist' => '',
  'Cannot delete parent category' => '',
  'Category has been deleted.' => '',
  'Category has been updated' => '',
  'Change optional parameters for a given theme.' => '',
  'Change the site theme for desktop, tablet, and mobile.' => '',
  'CiiMS is out of date. Please update to the latest version ({{version}})' => '',
  'CiiMS\' database is out of date. Please run yiic migrate up to migrate your database to the latest version.' => '',
  'Comments' => '',
  'Configure and verify how CiiMS sends emails.' => '',
  'Content has been updated.' => '',
  'Drafted Post' => '',
  'Email Settings' => '',
  'Enable and configure various Analytics providers (more coming soon!).' => '',
  'General Settings' => '',
  'In {{category}}' => '',
  'Insufficient data provided. Invalid request' => '',
  'Invalid Method' => '',
  'Manage Dashboard Cards' => '',
  'Manage and add new dashboard cards.' => '',
  'Missing POST data' => '',
  'Missing category id' => '',
  'No card type exists with that ID' => '',
  'No card with that ID exists' => '',
  'No comment with that id exists.' => '',
  'No records were supplied to delete' => '',
  'Please address the following issues.' => '',
  'Plugins are not yet supported' => '',
  'Post has been deleted' => '',
  'Provide Credentials for accessing and submitting data to various third party social media sites.' => '',
  'Runtime directory is not writable' => '',
  'Save Changes' => '',
  'Save Theme' => '',
  'Set basic information about your site and change global settings.' => '',
  'Social Settings' => '',
  'System Information' => '',
  'The requested page does not exist.' => '',
  'The requested theme type is not set. Please set a theme before attempting to change theme settings' => '',
  'Theme Settings' => '',
  'There are no dashboard cards with that id' => '',
  'There are no issues with your system. =)' => '',
  'There was an error in your submission, please verify you data before trying again.' => '',
  'There was an error saving your comment.' => '',
  'There was an error saving your content. Please try again.' => '',
  'There was an error saving your settings.' => '',
  'There was an unknown error processing your request' => '',
  'Unable to find valid card at that location.' => '',
  'Unable to save uploaded image.' => '',
  'User has been updated.' => '',
  'View system and diagnostic information.' => '',
  'We were unable to retrieve a post with that id. Please do not repeat this request again.' => '',
  'You do not have permission to access this card' => '',
  'You must specify a card to delete' => '',
  'Your request is invalid' => '',
  'Your runtime folder ({{folder}}) is not writable. Please change the permissions on the folder to be writable' => '',
  'Your settings have been updated.' => '',
  'Your uploads folder ({{folder}}) is not writable. Please change the permissions on the folder to be writable' => '',
  'approve' => '',
  'block' => '',
  'delete' => '',
  'now' => '',
);
